settings:
  recovery:
    index: true
    events: false
    tools: false
  legacy:
    force: false
    interval: 0s
schema:
- name: kudaki-gateway-service
  path: .
  commands:
    clean:
      status: true
    run:
      status: true
  args:
  - -- ADDRESS 0.0.0.0
  - -- GRPC_PORT 9000
  - -- REST_PORT 9001
  - -- KAFKA_BROKERS 178.62.107.160:29092
  - -- USER_AUTH_SERVICE_GRPC_ADDRESS localhost:9099
  - -- KAFKA_VERSION 2.1.1
  - -- REDISEARCH_SERVER 178.62.107.160:6379
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
    - deployment
    - .vendor-new
    scripts:
    - type: before
      command: taskkill /IM "kudaki-gateway-service.exe" /F